CREATE TABLE [dbo].[AI_FactUsageDaily](
	[DimDateKey] [int] NULL,
	[DimSubscriptionKey] [int] NULL,
	[DimTenantKey] [int] NULL,
	[DimAccountKey] [int] NULL,
	[DimOfferKey] [int] NULL,
	[BillingDimGeographyKey] [int] NULL,
	[ServiceUseDimGeographyKey] [int] NULL,
	[TenantDimGeographyKey] [int] NULL,
	[AccountDimGeographyKey] [int] NULL,
	[DimInfoFieldKey] [int] NULL,
	[DimRatingParameterKey] [int] NULL,
	[DimServiceKey] [int] NULL,
	[DimBillingSystemKey] [int] NULL,
	[TotalUnits] [numeric](18, 8) NULL,
	[AI_SQLStorageMB] [numeric](18, 8) NULL,
	[AI_NormalizedUsage] [numeric](18, 10) NULL,
	[AIMeta_CreatedAt] [datetime2](7) NULL,
	[AIMeta_UpdatedAt] [datetime2](7) NULL,
	[AIMeta_CreatedDimAuditKey] [bigint] NULL,
	[AIMeta_UpdatedDimAuditKey] [bigint] NULL,
	[ResourceGUID] [uniqueidentifier] NULL,
	[DimImageTypeKey] [int] NULL,
	[DimLocationKey] [int] NULL,
	[DimMeteredServiceKey] [int] NULL,
	[DimProjectKey] [int] NULL
) ON [PRIMARY]
