CREATE PROCEDURE [dbo].[ETL_sp_WareHouseIncidents_MergeFromTemp]
	@ETLId INT
AS
	
	SET NOCOUNT ON;
	-- Temp table to record changes
	CREATE TABLE #MyTempTable
	(  
		[ActionTaken] nvarchar(10),
		[IncidentId] bigint
	)

	-- Merge by Insert and Update
    MERGE [dbo].[WarehouseIncidents] AS target
    USING 
	(SELECT * FROM [WarehouseIncidents_Temp]) 
	AS source ([IncidentId]
			  ,[SourceName]
			  ,[SourceType]
			  ,[SourceIncidentId]
			  ,[SourceCreateDate]
			  ,[SourceOrigin]
			  ,[SourceCreatedBy]
			  ,[SourceModifiedDate]
			  ,[CreateDate]
			  ,[ModifiedDate]
			  ,[RoutingId]
			  ,[CorrelationId]
			  ,[OccurringEnvironment]
			  ,[OccurringDatacenter]
			  ,[OccurringDeviceGroup]
			  ,[OccurringDeviceName]
			  ,[OccurringServiceInstanceId]
			  ,[RaisingEnvironment]
			  ,[RaisingDatacenter]
			  ,[RaisingDeviceGroup]
			  ,[RaisingDeviceName]
			  ,[RaisingServiceInstanceId]
			  ,[OwningTenantName]
			  ,[OwningTeamName]
			  ,[OwningContactAlias]
			  ,[ParentIncidentId]
			  ,[Severity]
			  ,[Status]
			  ,[IsNoise]
			  ,[IsSecurityRisk]
			  ,[IsCustomerImpacting]
			  ,[Component]
			  ,[Revision]
			  ,[TsgId]
			  ,[Title]
			  ,[ReproSteps]
			  ,[CustomerName]
			  ,[CommitDate]
			  ,[ResolveDate]
			  ,[ResolvedBy]
			  ,[RootCauseId]
			  ,[RootCauseLinkDate]
			  ,[Mitigation]
			  ,[KBArticleId]
			  ,[PIRReportId]
			  ,[PIRLinkDate]
			  ,[ImpactedScenarios]
			  ,[HitCount]
			  ,[LastCorrelationDate]
			  ,[Keywords]
			  ,[MitigateDate]
			  ,[ImpactStartDate]
			  ,[MitigatedBy]
			  ,[CommsMgrEngagementMode]
			  ,[CommsMgrEngagementAdditionalDetails]
			  ,[IncidentType]
			  ,[ChildCount]
			  ,[RelatedLinksCount]
			  ,[ExternalLinksCount]
			  ,[HowFixed]
			  ,[IncidentSubType]
			  ,[TsgOutput]
			  ,[MonitorId]
			  ,[ResponsibleTenantName]
			  ,[SupportTicketId]
			  ,[SubscriptionId]
			  ,[WarehouseModifiedDate]
			  ,[PublicPirId]
			  ,[OriginatingTenantName])
    ON (target.[IncidentId] = source.[IncidentId])
    
	-- MATCHED
	WHEN MATCHED THEN 
        UPDATE SET	[SourceName]=source.[SourceName]
					,[SourceType]=source.[SourceType]
					,[SourceIncidentId]=source.[SourceIncidentId]
					,[SourceCreateDate]=source.[SourceCreateDate]
					,[SourceOrigin]=source.[SourceOrigin]
					,[SourceCreatedBy]=source.[SourceCreatedBy]
					,[SourceModifiedDate]=source.[SourceModifiedDate]
					,[CreateDate]=source.[CreateDate]
					,[ModifiedDate]=source.[ModifiedDate]
					,[RoutingId]=source.[RoutingId]
					,[CorrelationId]=source.[CorrelationId]
					,[OccurringEnvironment]=source.[OccurringEnvironment]
					,[OccurringDatacenter]=source.[OccurringDatacenter]
					,[OccurringDeviceGroup]=source.[OccurringDeviceGroup]
					,[OccurringDeviceName]=source.[OccurringDeviceName]
					,[OccurringServiceInstanceId]=source.[OccurringServiceInstanceId]
					,[RaisingEnvironment]=source.[RaisingEnvironment]
					,[RaisingDatacenter]=source.[RaisingDatacenter]
					,[RaisingDeviceGroup]=source.[RaisingDeviceGroup]
					,[RaisingDeviceName]=source.[RaisingDeviceName]
					,[RaisingServiceInstanceId]=source.[RaisingServiceInstanceId]
					,[OwningTenantName]=source.[OwningTenantName]
					,[OwningTeamName]=source.[OwningTeamName]
					,[OwningContactAlias]=source.[OwningContactAlias]
					,[ParentIncidentId]=source.[ParentIncidentId]
					,[Severity]=source.[Severity]
					,[Status]=source.[Status]
					,[IsNoise]=source.[IsNoise]
					,[IsSecurityRisk]=source.[IsSecurityRisk]
					,[IsCustomerImpacting]=source.[IsCustomerImpacting]
					,[Component]=source.[Component]
					,[Revision]=source.[Revision]
					,[TsgId]=source.[TsgId]
					,[Title]=source.[Title]
					,[ReproSteps]=source.[ReproSteps]
					,[CustomerName]=source.[CustomerName]
					,[CommitDate]=source.[CommitDate]
					,[ResolveDate]=source.[ResolveDate]
					,[ResolvedBy]=source.[ResolvedBy]
					,[RootCauseId]=source.[RootCauseId]
					,[RootCauseLinkDate]=source.[RootCauseLinkDate]
					,[Mitigation]=source.[Mitigation]
					,[KBArticleId]=source.[KBArticleId]
					,[PIRReportId]=source.[PIRReportId]
					,[PIRLinkDate]=source.[PIRLinkDate]
					,[ImpactedScenarios]=source.[ImpactedScenarios]
					,[HitCount]=source.[HitCount]
					,[LastCorrelationDate]=source.[LastCorrelationDate]
					,[Keywords]=source.[Keywords]
					,[MitigateDate]=source.[MitigateDate]
					,[ImpactStartDate]=source.[ImpactStartDate]
					,[MitigatedBy]=source.[MitigatedBy]
					,[CommsMgrEngagementMode]=source.[CommsMgrEngagementMode]
					,[CommsMgrEngagementAdditionalDetails]=source.[CommsMgrEngagementAdditionalDetails]
					,[IncidentType]=source.[IncidentType]
					,[ChildCount]=source.[ChildCount]
					,[RelatedLinksCount]=source.[RelatedLinksCount]
					,[ExternalLinksCount]=source.[ExternalLinksCount]
					,[HowFixed]=source.[HowFixed]
					,[IncidentSubType]=source.[IncidentSubType]
					,[TsgOutput]=source.[TsgOutput]
					,[MonitorId]=source.[MonitorId]
					,[ResponsibleTenantName]=source.[ResponsibleTenantName]
					,[SupportTicketId]=source.[SupportTicketId]
					,[SubscriptionId]=source.[SubscriptionId]
					,[WarehouseModifiedDate]=source.[WarehouseModifiedDate]
					,[PublicPirId]=source.[PublicPirId]
					,[OriginatingTenantName]=source.[OriginatingTenantName]

	-- NOT MATCHED
	WHEN NOT MATCHED THEN
    INSERT ([IncidentId]
			,[SourceName]
			,[SourceType]
			,[SourceIncidentId]
			,[SourceCreateDate]
			,[SourceOrigin]
			,[SourceCreatedBy]
			,[SourceModifiedDate]
			,[CreateDate]
			,[ModifiedDate]
			,[RoutingId]
			,[CorrelationId]
			,[OccurringEnvironment]
			,[OccurringDatacenter]
			,[OccurringDeviceGroup]
			,[OccurringDeviceName]
			,[OccurringServiceInstanceId]
			,[RaisingEnvironment]
			,[RaisingDatacenter]
			,[RaisingDeviceGroup]
			,[RaisingDeviceName]
			,[RaisingServiceInstanceId]
			,[OwningTenantName]
			,[OwningTeamName]
			,[OwningContactAlias]
			,[ParentIncidentId]
			,[Severity]
			,[Status]
			,[IsNoise]
			,[IsSecurityRisk]
			,[IsCustomerImpacting]
			,[Component]
			,[Revision]
			,[TsgId]
			,[Title]
			,[ReproSteps]
			,[CustomerName]
			,[CommitDate]
			,[ResolveDate]
			,[ResolvedBy]
			,[RootCauseId]
			,[RootCauseLinkDate]
			,[Mitigation]
			,[KBArticleId]
			,[PIRReportId]
			,[PIRLinkDate]
			,[ImpactedScenarios]
			,[HitCount]
			,[LastCorrelationDate]
			,[Keywords]
			,[MitigateDate]
			,[ImpactStartDate]
			,[MitigatedBy]
			,[CommsMgrEngagementMode]
			,[CommsMgrEngagementAdditionalDetails]
			,[IncidentType]
			,[ChildCount]
			,[RelatedLinksCount]
			,[ExternalLinksCount]
			,[HowFixed]
			,[IncidentSubType]
			,[TsgOutput]
			,[MonitorId]
			,[ResponsibleTenantName]
			,[SupportTicketId]
			,[SubscriptionId]
			,[WarehouseModifiedDate]
			,[PublicPirId]
			,[OriginatingTenantName])
    VALUES (source.[IncidentId]
			,source.[SourceName]
			,source.[SourceType]
			,source.[SourceIncidentId]
			,source.[SourceCreateDate]
			,source.[SourceOrigin]
			,source.[SourceCreatedBy]
			,source.[SourceModifiedDate]
			,source.[CreateDate]
			,source.[ModifiedDate]
			,source.[RoutingId]
			,source.[CorrelationId]
			,source.[OccurringEnvironment]
			,source.[OccurringDatacenter]
			,source.[OccurringDeviceGroup]
			,source.[OccurringDeviceName]
			,source.[OccurringServiceInstanceId]
			,source.[RaisingEnvironment]
			,source.[RaisingDatacenter]
			,source.[RaisingDeviceGroup]
			,source.[RaisingDeviceName]
			,source.[RaisingServiceInstanceId]
			,source.[OwningTenantName]
			,source.[OwningTeamName]
			,source.[OwningContactAlias]
			,source.[ParentIncidentId]
			,source.[Severity]
			,source.[Status]
			,source.[IsNoise]
			,source.[IsSecurityRisk]
			,source.[IsCustomerImpacting]
			,source.[Component]
			,source.[Revision]
			,source.[TsgId]
			,source.[Title]
			,source.[ReproSteps]
			,source.[CustomerName]
			,source.[CommitDate]
			,source.[ResolveDate]
			,source.[ResolvedBy]
			,source.[RootCauseId]
			,source.[RootCauseLinkDate]
			,source.[Mitigation]
			,source.[KBArticleId]
			,source.[PIRReportId]
			,source.[PIRLinkDate]
			,source.[ImpactedScenarios]
			,source.[HitCount]
			,source.[LastCorrelationDate]
			,source.[Keywords]
			,source.[MitigateDate]
			,source.[ImpactStartDate]
			,source.[MitigatedBy]
			,source.[CommsMgrEngagementMode]
			,source.[CommsMgrEngagementAdditionalDetails]
			,source.[IncidentType]
			,source.[ChildCount]
			,source.[RelatedLinksCount]
			,source.[ExternalLinksCount]
			,source.[HowFixed]
			,source.[IncidentSubType]
			,source.[TsgOutput]
			,source.[MonitorId]
			,source.[ResponsibleTenantName]
			,source.[SupportTicketId]
			,source.[SubscriptionId]
			,source.[WarehouseModifiedDate]
			,source.[PublicPirId]
			,source.[OriginatingTenantName])

	--OUTPUT Parameters
    OUTPUT $action, inserted.[IncidentId] INTO #MyTempTable;

	DECLARE	@InsertedRows INT
	DECLARE @UpdatedRows INT
	SELECT @InsertedRows = COUNT(*) FROM #MyTempTable WHERE [ActionTaken] = 'INSERT'
	SELECT @UpdatedRows = COUNT(*) FROM #MyTempTable WHERE [ActionTaken] = 'UPDATE'
	
	-- Update Log
	UPDATE ETL_Log
		SET [InsertedRows] = @InsertedRows,
			[UpdatedRows] = @UpdatedRows
		WHERE [id] = @ETLId

 	DROP TABLE #MyTempTable

RETURN 0
