CREATE PROCEDURE [dbo].[ETL_MergeTemp_DimSubscription]
	@ETLId INT
AS

	SET NOCOUNT ON;
	-- Temp table to record changes
	CREATE TABLE #MyTempTable
	(  
		[ActionTaken] nvarchar(10),
		[IncidentId] bigint
	)

	-- Merge by Insert and Update
    MERGE [dbo].[DimSubscription] AS target
		USING (SELECT * FROM [DimSubscription_temp]) 
			AS source ([DimSubscriptionKey]
						,[DimBillingSystemKey]
						,[SubscriptionGUID]
						,[DataSource]
						,[SubscriptionName]
						,[SubscriptionCreatedDate]
						,[AnniversaryDate]
						,[AI_FirstUseDate]
						,[AI_FirstInvoiceDate]
						,[AI_SubscriptionCanceledDate]
						,[SubscriptionStartDate]
						,[SubscriptionEndDate]
						,[PaymentMethodType]
						,[NonRenewalReasonName]
						,[IsAutoRenew]
						,[HasTransitioned]
						,[IncludedQuantity]
						,[AllowedOverageQuantity]
						,[BillingCycle]
						,[FriendlySubscriptionName]
						,[SubscriptionStatusModifier]
						,[CustomerId]
						,[ChannelType]
						,[EndCustomerSubAccount]
						,[AI_IsTest]
						,[AI_BillingType]
						,[AI_AccountType]
						,[AI_PassStatus]
						,[AI_CreatedAsTrial]
						,[AI_TrialToPaidConversion]
						,[AI_TrialToPaidConversionDate]
						,[AI_SubscriptionStatus]
						,[AI_IsSupport]
						,[AIMeta_SCDIsCurrent]
						,[AIMeta_SCDEffectiveFrom]
						,[AIMeta_SCDEffectiveTo]
						,[DurableDimSubscriptionKey]
						,[OMSSubscriptionIdentifier]
						,[V1SubscriptionIdentifier]
						,[MINTSubscriptionIdentifier]
						,[OMSMINTSubscriptionIdentifier]
						,[i_billable_acct_id]
						,[si_subscription_ref_id]
						,[OmsAcctId]
						,[OmsSubscriptionId]
						,[CTPBDKID]
						,[MTSubscriptionAccountIdentifier]
						,[MTSubscriptionIdentifier]
						,[UXSubscriptionIdentifier]
						,[CurrentStateEndDate]
						,[ExternalSubscriptionIdentifier]
						,[ExternalData]
						,[AtlasIdentifier]
						,[RIOIdentifier]
						,[WebTrendsReferralSource]
						,[WebTrendsCampaignIdentifier]
						,[AccountSKUIdentifier]
						,[MonetaryCapReachedNotify]
						,[AdminPUID]
						,[AI_AdminPUIDWebtrendsHash]
						,[IsFraudIdentified]
						,[FraudIdentifiedDate]
						,[TPID]
						,[Tier1PartnerMPNId]
						,[Tier2PartnerMPNId]
						,[CAID]
						,[SubscriptionID]
						,[AI_IsCSP]
						,[AI_Locked]
						,[AIMeta_CreatedAt]
						,[AIMeta_UpdatedAt]
						,[AIMeta_CreatedDimAuditKey]
						,[AIMeta_UpdatedDimAuditKey]
)
				ON (target.[DimSubscriptionKey] = source.[DimSubscriptionKey])
    
	-- MATCHED
	WHEN MATCHED THEN 
        UPDATE SET	[DimSubscriptionKey]=	source.[DimSubscriptionKey]
					,[DimBillingSystemKey]=	source.[DimBillingSystemKey]
					,[SubscriptionGUID]=	source.[SubscriptionGUID]
					,[DataSource]=	source.[DataSource]
					,[SubscriptionName]=	source.[SubscriptionName]
					,[SubscriptionCreatedDate]=	source.[SubscriptionCreatedDate]
					,[AnniversaryDate]=	source.[AnniversaryDate]
					,[AI_FirstUseDate]=	source.[AI_FirstUseDate]
					,[AI_FirstInvoiceDate]=	source.[AI_FirstInvoiceDate]
					,[AI_SubscriptionCanceledDate]=	source.[AI_SubscriptionCanceledDate]
					,[SubscriptionStartDate]=	source.[SubscriptionStartDate]
					,[SubscriptionEndDate]=	source.[SubscriptionEndDate]
					,[PaymentMethodType]=	source.[PaymentMethodType]
					,[NonRenewalReasonName]=	source.[NonRenewalReasonName]
					,[IsAutoRenew]=	source.[IsAutoRenew]
					,[HasTransitioned]=	source.[HasTransitioned]
					,[IncludedQuantity]=	source.[IncludedQuantity]
					,[AllowedOverageQuantity]=	source.[AllowedOverageQuantity]
					,[BillingCycle]=	source.[BillingCycle]
					,[FriendlySubscriptionName]=	source.[FriendlySubscriptionName]
					,[SubscriptionStatusModifier]=	source.[SubscriptionStatusModifier]
					,[CustomerId]=	source.[CustomerId]
					,[ChannelType]=	source.[ChannelType]
					,[EndCustomerSubAccount]=	source.[EndCustomerSubAccount]
					,[AI_IsTest]=	source.[AI_IsTest]
					,[AI_BillingType]=	source.[AI_BillingType]
					,[AI_AccountType]=	source.[AI_AccountType]
					,[AI_PassStatus]=	source.[AI_PassStatus]
					,[AI_CreatedAsTrial]=	source.[AI_CreatedAsTrial]
					,[AI_TrialToPaidConversion]=	source.[AI_TrialToPaidConversion]
					,[AI_TrialToPaidConversionDate]=	source.[AI_TrialToPaidConversionDate]
					,[AI_SubscriptionStatus]=	source.[AI_SubscriptionStatus]
					,[AI_IsSupport]=	source.[AI_IsSupport]
					,[AIMeta_SCDIsCurrent]=	source.[AIMeta_SCDIsCurrent]
					,[AIMeta_SCDEffectiveFrom]=	source.[AIMeta_SCDEffectiveFrom]
					,[AIMeta_SCDEffectiveTo]=	source.[AIMeta_SCDEffectiveTo]
					,[DurableDimSubscriptionKey]=	source.[DurableDimSubscriptionKey]
					,[OMSSubscriptionIdentifier]=	source.[OMSSubscriptionIdentifier]
					,[V1SubscriptionIdentifier]=	source.[V1SubscriptionIdentifier]
					,[MINTSubscriptionIdentifier]=	source.[MINTSubscriptionIdentifier]
					,[OMSMINTSubscriptionIdentifier]=	source.[OMSMINTSubscriptionIdentifier]
					,[i_billable_acct_id]=	source.[i_billable_acct_id]
					,[si_subscription_ref_id]=	source.[si_subscription_ref_id]
					,[OmsAcctId]=	source.[OmsAcctId]
					,[OmsSubscriptionId]=	source.[OmsSubscriptionId]
					,[CTPBDKID]=	source.[CTPBDKID]
					,[MTSubscriptionAccountIdentifier]=	source.[MTSubscriptionAccountIdentifier]
					,[MTSubscriptionIdentifier]=	source.[MTSubscriptionIdentifier]
					,[UXSubscriptionIdentifier]=	source.[UXSubscriptionIdentifier]
					,[CurrentStateEndDate]=	source.[CurrentStateEndDate]
					,[ExternalSubscriptionIdentifier]=	source.[ExternalSubscriptionIdentifier]
					,[ExternalData]=	source.[ExternalData]
					,[AtlasIdentifier]=	source.[AtlasIdentifier]
					,[RIOIdentifier]=	source.[RIOIdentifier]
					,[WebTrendsReferralSource]=	source.[WebTrendsReferralSource]
					,[WebTrendsCampaignIdentifier]=	source.[WebTrendsCampaignIdentifier]
					,[AccountSKUIdentifier]=	source.[AccountSKUIdentifier]
					,[MonetaryCapReachedNotify]=	source.[MonetaryCapReachedNotify]
					,[AdminPUID]=	source.[AdminPUID]
					,[AI_AdminPUIDWebtrendsHash]=	source.[AI_AdminPUIDWebtrendsHash]
					,[IsFraudIdentified]=	source.[IsFraudIdentified]
					,[FraudIdentifiedDate]=	source.[FraudIdentifiedDate]
					,[TPID]=	source.[TPID]
					,[Tier1PartnerMPNId]=	source.[Tier1PartnerMPNId]
					,[Tier2PartnerMPNId]=	source.[Tier2PartnerMPNId]
					,[CAID]=	source.[CAID]
					,[SubscriptionID]=	source.[SubscriptionID]
					,[AI_IsCSP]=	source.[AI_IsCSP]
					,[AI_Locked]=	source.[AI_Locked]
					,[AIMeta_CreatedAt]=	source.[AIMeta_CreatedAt]
					,[AIMeta_UpdatedAt]=	source.[AIMeta_UpdatedAt]
					,[AIMeta_CreatedDimAuditKey]=	source.[AIMeta_CreatedDimAuditKey]
					,[AIMeta_UpdatedDimAuditKey]=	source.[AIMeta_UpdatedDimAuditKey]

	-- NOT MATCHED
	WHEN NOT MATCHED THEN
    INSERT ([DimSubscriptionKey]
			,[DimBillingSystemKey]
			,[SubscriptionGUID]
			,[DataSource]
			,[SubscriptionName]
			,[SubscriptionCreatedDate]
			,[AnniversaryDate]
			,[AI_FirstUseDate]
			,[AI_FirstInvoiceDate]
			,[AI_SubscriptionCanceledDate]
			,[SubscriptionStartDate]
			,[SubscriptionEndDate]
			,[PaymentMethodType]
			,[NonRenewalReasonName]
			,[IsAutoRenew]
			,[HasTransitioned]
			,[IncludedQuantity]
			,[AllowedOverageQuantity]
			,[BillingCycle]
			,[FriendlySubscriptionName]
			,[SubscriptionStatusModifier]
			,[CustomerId]
			,[ChannelType]
			,[EndCustomerSubAccount]
			,[AI_IsTest]
			,[AI_BillingType]
			,[AI_AccountType]
			,[AI_PassStatus]
			,[AI_CreatedAsTrial]
			,[AI_TrialToPaidConversion]
			,[AI_TrialToPaidConversionDate]
			,[AI_SubscriptionStatus]
			,[AI_IsSupport]
			,[AIMeta_SCDIsCurrent]
			,[AIMeta_SCDEffectiveFrom]
			,[AIMeta_SCDEffectiveTo]
			,[DurableDimSubscriptionKey]
			,[OMSSubscriptionIdentifier]
			,[V1SubscriptionIdentifier]
			,[MINTSubscriptionIdentifier]
			,[OMSMINTSubscriptionIdentifier]
			,[i_billable_acct_id]
			,[si_subscription_ref_id]
			,[OmsAcctId]
			,[OmsSubscriptionId]
			,[CTPBDKID]
			,[MTSubscriptionAccountIdentifier]
			,[MTSubscriptionIdentifier]
			,[UXSubscriptionIdentifier]
			,[CurrentStateEndDate]
			,[ExternalSubscriptionIdentifier]
			,[ExternalData]
			,[AtlasIdentifier]
			,[RIOIdentifier]
			,[WebTrendsReferralSource]
			,[WebTrendsCampaignIdentifier]
			,[AccountSKUIdentifier]
			,[MonetaryCapReachedNotify]
			,[AdminPUID]
			,[AI_AdminPUIDWebtrendsHash]
			,[IsFraudIdentified]
			,[FraudIdentifiedDate]
			,[TPID]
			,[Tier1PartnerMPNId]
			,[Tier2PartnerMPNId]
			,[CAID]
			,[SubscriptionID]
			,[AI_IsCSP]
			,[AI_Locked]
			,[AIMeta_CreatedAt]
			,[AIMeta_UpdatedAt]
			,[AIMeta_CreatedDimAuditKey]
			,[AIMeta_UpdatedDimAuditKey]
)
    VALUES (source.[DimSubscriptionKey]
			,source.[DimBillingSystemKey]
			,source.[SubscriptionGUID]
			,source.[DataSource]
			,source.[SubscriptionName]
			,source.[SubscriptionCreatedDate]
			,source.[AnniversaryDate]
			,source.[AI_FirstUseDate]
			,source.[AI_FirstInvoiceDate]
			,source.[AI_SubscriptionCanceledDate]
			,source.[SubscriptionStartDate]
			,source.[SubscriptionEndDate]
			,source.[PaymentMethodType]
			,source.[NonRenewalReasonName]
			,source.[IsAutoRenew]
			,source.[HasTransitioned]
			,source.[IncludedQuantity]
			,source.[AllowedOverageQuantity]
			,source.[BillingCycle]
			,source.[FriendlySubscriptionName]
			,source.[SubscriptionStatusModifier]
			,source.[CustomerId]
			,source.[ChannelType]
			,source.[EndCustomerSubAccount]
			,source.[AI_IsTest]
			,source.[AI_BillingType]
			,source.[AI_AccountType]
			,source.[AI_PassStatus]
			,source.[AI_CreatedAsTrial]
			,source.[AI_TrialToPaidConversion]
			,source.[AI_TrialToPaidConversionDate]
			,source.[AI_SubscriptionStatus]
			,source.[AI_IsSupport]
			,source.[AIMeta_SCDIsCurrent]
			,source.[AIMeta_SCDEffectiveFrom]
			,source.[AIMeta_SCDEffectiveTo]
			,source.[DurableDimSubscriptionKey]
			,source.[OMSSubscriptionIdentifier]
			,source.[V1SubscriptionIdentifier]
			,source.[MINTSubscriptionIdentifier]
			,source.[OMSMINTSubscriptionIdentifier]
			,source.[i_billable_acct_id]
			,source.[si_subscription_ref_id]
			,source.[OmsAcctId]
			,source.[OmsSubscriptionId]
			,source.[CTPBDKID]
			,source.[MTSubscriptionAccountIdentifier]
			,source.[MTSubscriptionIdentifier]
			,source.[UXSubscriptionIdentifier]
			,source.[CurrentStateEndDate]
			,source.[ExternalSubscriptionIdentifier]
			,source.[ExternalData]
			,source.[AtlasIdentifier]
			,source.[RIOIdentifier]
			,source.[WebTrendsReferralSource]
			,source.[WebTrendsCampaignIdentifier]
			,source.[AccountSKUIdentifier]
			,source.[MonetaryCapReachedNotify]
			,source.[AdminPUID]
			,source.[AI_AdminPUIDWebtrendsHash]
			,source.[IsFraudIdentified]
			,source.[FraudIdentifiedDate]
			,source.[TPID]
			,source.[Tier1PartnerMPNId]
			,source.[Tier2PartnerMPNId]
			,source.[CAID]
			,source.[SubscriptionID]
			,source.[AI_IsCSP]
			,source.[AI_Locked]
			,source.[AIMeta_CreatedAt]
			,source.[AIMeta_UpdatedAt]
			,source.[AIMeta_CreatedDimAuditKey]
			,source.[AIMeta_UpdatedDimAuditKey]
			)

	--OUTPUT Parameters
    OUTPUT $action, inserted.[DimSubscriptionKey] INTO #MyTempTable;

	DECLARE	@InsertedRows INT
	DECLARE @UpdatedRows INT
	SELECT @InsertedRows = COUNT(*) FROM #MyTempTable WHERE [ActionTaken] = 'INSERT'
	SELECT @UpdatedRows = COUNT(*) FROM #MyTempTable WHERE [ActionTaken] = 'UPDATE'
	
	-- Update Log
	UPDATE ETL_Log
		SET [DimSubscription_InsertedRows] = @InsertedRows,
			[DimSubscription_UpdatedRows] = @UpdatedRows
		WHERE [id] = @ETLId

 	DROP TABLE #MyTempTable


	
RETURN 0
