CREATE VIEW [dbo].[v_CSS_Data_CDN_MySQL_Tickets]
	AS SELECT CASE WHEN [ParentIssueCode]='MySql Database On Azure' THEN 'MySql' ELSE 'CDN' END AS [ServiceType] 
			,[Case_ID]
			,[AssignedTo]
			,[FromQueue]
			,[AssignedTeam]
			,[CreatedTime]
			,[ClosedTime]
			,[SolutionDeliveredTime]
			,[LastUpdatedTime]
			,[IssueCode]
			,[ParentIssueCode]
			,[Title]
			,[Description]
			,[InquiryType]
			,[CaseStatus]
			,[OpenClose]
			,[ExternalStatus]
			,[Stage]
			,[ProductType]
			,[ProductName]
			,[OrgID]
			,[Severity]
			,[CustomerType]
			,[FeedBack]
			,[ReactivationCount]
			,[EscalatetoMS]
			,[MSLed]
			,[InitialResponseDate]
			,[SupportType]
			,[SolutionOfferedTime]
			,[SolutionConfirmedTime]
			,[SubscriptionGUID]
			,[CPERank]
			,[TBCount]
			,[BBCount]
			,[SurveyResponseCount]
			,[YearMonthofCreate]
			,[YearMonthofClose]
			,[EscalationCount]
			,[DTC]
			,[DTS]
			,[FirstDayResolution]
			,[OpenningMoreThan7Days]
			,[OpenningDays]
			,[OpeningCount]
			,[ClosedCount]
			,[TMPI]
			,[OutageRelated]
			,[Severity_A_Count]
		FROM [v_CSS_Data_Mooncake_KPI] 
		WHERE [ParentIssueCode]='MySql Database On Azure' 
			OR [IssueCode] LIKE '%CDN%' 
			OR [ParentIssueCode] LIKE '%CDN%' 
			OR [Title] LIKE '%CDN%' 
			OR InquiryType LIKE '%CDN%'
