
CREATE VIEW [dbo].[v_CSS_Data_Detail]
AS
	SELECT ROW_NUMBER() OVER (PARTITION BY [CASE_ID] ORDER BY [LASTUPDATEDATE] DESC) AS ROWNUMBER
		,[id]
		,[InsertDate]
		,[Case_ID]
		,[CurrentOwner_ID] AS [AssignedTo]
		,[FromQueue]
		,[ToQueue] AS [AssignedTeam]
		,[CreateDate] AS [CreatedTime]
		,[ClosedDate] AS [ClosedTime]
		,[SolutionDeliveredDate] AS [SolutionDeliveredTime]
		,[LastUpdateDate] AS [LastUpdatedTime]
		,[IssueCode]
		,[ParentIssueCode]
		,[Title]
		,[IssueDescription] AS [Description]
		,[InquiryType]
		,[CaseStatus]
		,[Open/Close] AS [OpenClose]
		,CASE [CaseStatus] WHEN 'Solution Delivered' THEN 'SolutionDelivered' ELSE [Open/Close] END AS [ExternalStatus]
		,[CaseStatus] AS [Stage]
		,[ProductType]
		,[ProductName]
		,[OrgID]
		,RIGHT([OrgID],LEN([OrgID])- CHARINDEX('@',[OrgID])) AS [CreatedBy]
		,[SubscriptionID]
		,[Severity]
		,[CustomerType]
		,[FeedBack]
		,[LaborTime] AS [TotalLaborMinutes]
		,[ReactiveCount] AS [ReactivationCount]
		,[EscalatetoMS]
		,[MSLed]
		,[CaseSource]
		,[ReferenceID]
		,[MssolveID]
		,[TfsID]
		,[CorreCaseID]
		,[InitialResponseDate]
		,[SupportType]
		,[SolutionOfferedTime]
		,[SolutionConfirmedTime]
	FROM [DBO].[CSS_Data_Detail]