CREATE VIEW [dbo].[v_Mooncake_Support_System_Standard_Schema]
	AS SELECT Case_ID AS IncidentId,
			SourceName,
			LastUpdatedTime,
			Title,
			CreatedTime,
			CreatedBy,
			ExternalStatus,
			Stage,
			ProductType AS ProductArea,
			ProductName,
			Description,
			PlanId,
			InitialTopic,
			CurrentTopic,
			RootCause,
			Symptom,
			ResourceId,
			InitialResponseTime,
			ScopeDeliveredTime,
			SolutionDeliveredTime,
			ClosedTime,
			ReactivationCount,
			OwnershipChanges,
			OutageRelated,
			TotalLaborMinutes,
			CustomerLocation,
			Severity,
			AssignedTo,
			AssignedTeam,
			IncidentType
		FROM [dbo].[v_Mooncake_Support_Tickets]
