CREATE VIEW [dbo].[v_Mooncake_Support_Plan]
	AS SELECT '1' AS [PlanId]
			,'Manual' AS [SourceName]
			,'2015-12-08 12:25' AS [InsertDate]
			,'2015-12-08 12:25' AS [LastUpdatedTime] 
			,NULL AS [SubscriptionId] 
			,NULL AS [StartDate]
			,NULL AS [EndDate] 
			,'Active' AS [Status] 
			,'Free' AS [Type]
			,0 AS [IsPaid]


	--select [OfferID] as [PlanId]
    --  ,[DataSource] as [SourceName]
    --  ,[AI_FirstUseDate] as [InsertDate]
    --  ,[LastUpdatedTime]
    --  ,[SubscriptionGUID] as [SubscriptionId]
    --  ,[StartDate]
    --  ,[EndDate]
    --  ,[Status]
    --  ,[Type]
    --  ,[AI_TrialToPaidConversion] as [IsPaid]
	--from [dbo].[DimOffer]

