CREATE VIEW [dbo].[v_Mooncake_Support_Tickets]
	AS SELECT 'Mooncake Support System' AS [SourceName] 
		,1 AS [ROWNUMBER]
      ,1 AS [id]
      ,GETDATE() AS [InsertDate]
      ,[Case_ID]
      ,[AssignedTo]
      ,[FromQueue]
      ,[AssignedTeam]
      ,[CreatedTime]
      ,[ClosedTime]
      ,[SolutionDeliveredTime]
      ,[LastUpdatedTime]
      ,[IssueCode]
      ,[ParentIssueCode]
      ,[Title]
      ,[Description]
      ,[InquiryType]
      ,[CaseStatus]
      ,[OpenClose]
      ,[ExternalStatus]
      ,[Stage]
      ,[ProductType]
      ,[ProductName]
      ,'' AS [OrgID] -- Remove Confidential data
      ,[CreatedBy]
      ,[SubscriptionID]
      ,[Severity]
      ,[CustomerType]
      ,[FeedBack]
      ,[TotalLaborMinutes]
      ,[ReactivationCount]
      ,[EscalatetoMS]
      ,[MSLed]
      ,[CaseSource]
      ,[CPERank]
      ,[TBCount]
      ,[BBCount]
      ,[SurveyResponseCount]
      ,[YearofCreate]
      ,[MonthofCreate]
      ,[YearMonthofCreate]
      ,[YearofClose]
      ,[MonthofClose]
      ,[YearMonthofClose]
      ,[EscalationCount]
      ,[DTC]
      ,[DTS]
      ,[FirstDayResolution]
      ,[OpenningMoreThan7Days]
      ,[OpenningDays]
      ,[OpeningCount]
      ,[ClosedCount]
      ,[Resolution]
      ,[TMPI]
      ,[OwnershipChanges]
      ,[DateOfCreate]
      ,[DateOfClosed]
      ,[InitialResponseDate] AS [InitialResponseTime] 
	  ,[OutageRelated]
	,'China' AS [CustomerLocation]
		------------Above are from [v_CSS_Data_Mooncake]---
		,'1' AS [PlanId]
		,'' AS [InitialTopic]
		,[IssueCodeFullPath] AS [CurrentTopic]
		,'' AS [RootCause]
		,'' AS [Symptom]
		,'' AS [ResourceId]
		,NULL AS [ScopeDeliveredTime]
		,'' AS [IncidentType]
	FROM [v_CSS_Data_Mooncake]
